name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .env files
        run: |
          cp ui/.env.template ui/.env

      - name: Build Docker image
        run: |
          docker compose build

      - name: Run container
        # Need to run it in detached mode so that the workflow is not blocked.
        run: |
          docker compose up -d

      - name: Wait for FastAPI to start
        run: |
          sleep 5

      - name: Check running ports
        run: |
          sudo netstat -tulpn

      - name: Show logs on failure
        if: failure()
        run: docker compose logs -t
